name: Release gem

on:
  push:
    tags:
      - '*'

jobs:
  Tests:
    uses: enspirit/wlang/.github/workflows/integration.yml@master

  RubyGems:
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true

      - name: Build gem
        id: build-gem
        run: make gem

      - name: Release Gem
        uses: cadwallion/publish-rubygems-action@master
        id: gem-push
        env:
          RUBYGEMS_API_KEY: ${{ secrets.RUBYGEMS_API_KEY }}
          RELEASE_COMMAND: make gem.push

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()

  Github:
    needs: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: act10ns/slack@v1
        with:
          status: starting
          channel: '#opensource-cicd'

      - uses: actions/checkout@v2

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.4
          bundler-cache: true

      - name: Build packages
        run: make gem
        id: build-gem

      - uses: ncipollo/release-action@v1
        id: create-release
        with:
          artifacts: "pkg/*"
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#opensource-cicd'
        if: always()
